In [1]:
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
B = array([[1, 3, 5], [2, 4, 6]])
A + B

array([[ 2,  5,  8],
       [ 6,  9, 12]])

In [2]:
2 * A

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [3]:
0 * A

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
-1 * A

array([[-1, -2, -3],
       [-4, -5, -6]])