In [1]:
from numpy import array
A = [[1, 2, 3], [4, 5, 6]]; A

[[1, 2, 3], [4, 5, 6]]

In [2]:
A = array(A); A

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
print(A)

[[1 2 3]
 [4 5 6]]


In [4]:
L = A.tolist(); L

[[1, 2, 3], [4, 5, 6]]

In [5]:
B = A.copy(); B

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
A == B

array([[ True,  True,  True],
       [ True,  True,  True]])

In [7]:
(A == B).all()

True

In [8]:
B[0, 1] = 1
(A == B).all()

False