In [1]:
from numpy import array
A = array([1, 2, 3]); A

array([1, 2, 3])

In [2]:
B = A.reshape((1, 3)); B

array([[1, 2, 3]])

In [3]:
C = B.reshape((3, 1)); C

array([[1],
       [2],
       [3]])

In [4]:
D = C.reshape((3,)); D

array([1, 2, 3])

In [5]:
A[0] = 0; A

array([0, 2, 3])

In [6]:
B[0, 0], C[0, 0], D[0]

(0, 0, 0)