In [1]:
from numpy.linalg import eig, norm
A = [[3, -2, 2], [2, -1, 4], [2, -2, 1]]
lmd, vec = eig(A)
lmd

array([1.+0.j, 1.+2.j, 1.-2.j])

In [2]:
vec[:, 0]

array([ 7.07106781e-01+0.j,  7.07106781e-01+0.j, -3.65101269e-16+0.j])

In [3]:
vec[:, 1]

array([-0.47434165-0.15811388j, -0.79056942+0.j        ,
       -0.15811388-0.31622777j])

In [4]:
vec[:, 2]

array([-0.47434165+0.15811388j, -0.79056942-0.j        ,
       -0.15811388+0.31622777j])

In [5]:
[norm(vec[:, n]) for n in range(3)]

[1.0, 1.0, 1.0]