In [1]:
A = [[1, 2], [2, 1]]
from numpy.linalg import inv
inv(A)

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

In [2]:
from numpy import matrix
matrix(A)**(-1)

matrix([[-0.33333333,  0.66666667],
        [ 0.66666667, -0.33333333]])

In [3]:
matrix(A)**2

matrix([[5, 4],
        [4, 5]])