In [1]:
from numpy import *

In [2]:
A = array([1, 2, 3]); A

array([1, 2, 3])

In [3]:
print(A)

[1 2 3]


In [4]:
str(A)

'[1 2 3]'

In [5]:
repr(A)

'array([1, 2, 3])'

In [6]:
eval('array([1, 2, 3])')

array([1, 2, 3])