In [1]:
from numpy import *
A = array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
Lmd, V = linalg.eig(A); Lmd

array([ 9.62347538e+00, -6.23475383e-01,  1.78970268e-16])

In [2]:
linalg.inv(V).dot(A.dot(V))

array([[ 9.62347538e+00, -3.02068765e-15,  3.92073229e-16],
       [-1.25900917e-15, -6.23475383e-01,  1.87877276e-17],
       [ 1.59077352e-15,  2.88819870e-16,  9.24446373e-32]])

In [3]:
B = array([[1j, 1j], [-1j, 1j]])
Lmd, V = linalg.eigh(B); Lmd

array([-1.,  1.])

In [4]:
V.T.conj().dot(B.dot(V))

array([[-1.+1.j,  0.+0.j],
       [ 0.+0.j,  1.+1.j]])